# Let's provide a quick tour of Numpy

##### There is a lot more to numpy. Check out the official docs here: https://numpy.org/doc/stable/

### Import numpy

In [3]:
!conda install numpy -y

In [4]:
import numpy as np

### Create some random data

In [13]:
X = np.random.rand(4, 20)

In [14]:
X

array([[0.92439202, 0.42301613, 0.78393172, 0.44179879, 0.02259457,
        0.32262132, 0.21800757, 0.54307625, 0.45231825, 0.5023215 ,
        0.44825997, 0.18563643, 0.71866707, 0.8743183 , 0.89872197,
        0.7383638 , 0.30956885, 0.42315437, 0.01233925, 0.43131497],
       [0.71852459, 0.20235018, 0.05066127, 0.62635084, 0.99897546,
        0.21939586, 0.68956545, 0.06083324, 0.7028063 , 0.19406162,
        0.97114999, 0.26832841, 0.9067692 , 0.60051322, 0.15163001,
        0.37326017, 0.32152136, 0.57391919, 0.03768666, 0.81100051],
       [0.30882907, 0.525554  , 0.57532427, 0.26655367, 0.84989498,
        0.55536954, 0.38251368, 0.35961804, 0.79680849, 0.85786082,
        0.09322322, 0.2667367 , 0.97107657, 0.81292242, 0.51966205,
        0.80469264, 0.13679313, 0.3866799 , 0.93812857, 0.66204543],
       [0.0251668 , 0.16289911, 0.08252049, 0.92709477, 0.62864598,
        0.84750938, 0.00528755, 0.57528142, 0.88964458, 0.00668728,
        0.73816489, 0.31287837, 0.30596061, 0

### Make a selection of the idx 0 column

In [27]:
X[:,0]

array([0.92439202, 0.71852459, 0.30882907, 0.0251668 ])

### Make a selection of the idx 1 row

In [28]:
X[1,:]

array([0.71852459, 0.20235018, 0.05066127, 0.62635084, 0.99897546,
       0.21939586, 0.68956545, 0.06083324, 0.7028063 , 0.19406162,
       0.97114999, 0.26832841, 0.9067692 , 0.60051322, 0.15163001,
       0.37326017, 0.32152136, 0.57391919, 0.03768666, 0.81100051])

### sum all numbers in the array

In [29]:
X.sum()

38.892469186878046

### sum all numbers in the array across the columns

In [30]:
X.sum(axis=1)

array([ 9.67442309,  9.47930353, 11.0702872 ,  8.66845537])